name: CD

on:
  push:
    branches:
      - main

jobs:
  build_release:
    name: 'Build release .apk with debug signing'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.INTEGRATION_SSH_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
          cache: gradle
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Make gradlew executable
        run: chmod +x ./android/gradlew
      - name: Gradle build
        run: npm run build:android:assemble:prod:release -- --no-daemon
      - name: Retrieve version
        run: |
          cd ./android
          echo "VERSION_NAME=$(./gradlew -q printVersionName | grep 'App version:' | awk -F' ' '{print $NF}' | tr -d '\n')" >> "$GITHUB_ENV"
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_NAME }}
          files: './android/app/build/outputs/apk/prod/release/*.apk'
